services:
  - type: web
    name: property-management-app
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_PATH
        value: /opt/render/projectroot/property_management.db
      - key: ADMIN_USERNAME
        value: Admin
      - key: ADMIN_PASSWORD
        generateValue: true
      - key: ADMIN_EMAIL
        value: admin@system.com 